language: python

before_install:
  - sudo apt-get update
  - sudo pip install virtualenv
  - pip --version
  - virtualenv venv
  - virtualenv --version
  - source venv/bin/activate

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - python db_create.py
  - python unit_tests.py
  - python integration_tests.py
