language: python

before_install:
  - sudo apt-get -qq update
  - sudo pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python db_create.py

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - python unit_tests.py
  - python integration_tests.py
